// src/frontend/apps/app-web/src/app/pages/database-structure/data-preview-table.tsx
import { Table, Typography } from "@douyinfe/semi-ui";
import type { ColumnProps } from "@douyinfe/semi-ui/lib/es/table";
import type { PreviewDataResponse } from "../../../services/api-database-structure";

const { Text } = Typography;

export function DataPreviewTable({ data }: { data: PreviewDataResponse }) {
  const rows = data.rows.map((row, index) => ({
    __rowKey: String(index),
    ...row
  }));

  const columns: ColumnProps<Record<string, unknown>>[] = data.columns.map(column => ({
    title: column.name,
    dataIndex: column.name,
    width: 180,
    render: (value: unknown) => {
      if (value == null) {
        return <Text type="tertiary">NULL</Text>;
      }

      const text = String(value);
      return <Text ellipsis={{ showTooltip: true }}>{text.length > 240 ? `${text.slice(0, 240)}...` : text}</Text>;
    }
  }));

  return (
    <div className="database-center-table-scroll">
      <Table
        rowKey="__rowKey"
        columns={columns}
        dataSource={rows}
        pagination={false}
        size="small"
        scroll={{ x: Math.max(720, columns.length * 180) }}
      />
    </div>
  );
}

// src/frontend/apps/platform-web/src/pages/settings/components/DataPreviewTable.vue
<template>
  <a-table
    :columns="tableColumns"
    :data-source="data"
    :loading="loading"
    :scroll="{ x: 'max-content', y: 400 }"
    size="small"
    bordered
    :pagination="paginationConfig"
    :row-key="(_: unknown, index: number) => index"
  >
    <template #headerCell="{ column }">
      <span :title="`${column.title} (${column.colType})`">
        {{ column.title }}
        <span class="col-type-hint">{{ column.colType }}</span>
      </span>
    </template>
  </a-table>
</template>

<script setup lang="ts">
import { computed } from "vue";
import type { SqlQueryResultColumn } from "@atlas/shared-core";

const props = defineProps<{
  columns: SqlQueryResultColumn[];
  data: Record<string, unknown>[];
  loading: boolean;
}>();

const tableColumns = computed(() =>
  props.columns.map((column) => ({
    title: column.title,
    dataIndex: column.field,
    key: column.field,
    colType: column.type,
    ellipsis: true,
    width: 150
  }))
);

const paginationConfig = computed(() =>
  props.data.length > 50
    ? {
        pageSize: 50,
        showSizeChanger: true,
        pageSizeOptions: ["50", "100", "200", "500"],
        showTotal: (total: number) => `${total}`
      }
    : false
);
</script>

<style scoped>
.col-type-hint {
  font-size: 11px;
  color: #999;
  font-weight: normal;
  margin-left: 4px;
}
</style>
